/** CITO catalog: course title → USD price (matches payment form list). */
export const CITO_COURSE_CATALOG: ReadonlyArray<{
  readonly name: string;
  readonly price: number;
}> = [
  { name: "AI (Artificial Intelligence)", price: 25 },
  { name: "Internet & E-mail", price: 10 },
  { name: "Make Money Online (MMO)", price: 116 },
  { name: "Microsoft Word", price: 20 },
  { name: "Microsoft Excel", price: 20 },
  { name: "Microsoft PowerPoint", price: 15 },
  { name: "Advance Word", price: 25 },
  { name: "Advance Excel", price: 40 },
  { name: "W+E+P+Internet", price: 45.5 },
  { name: "MS Access Level I", price: 35 },
  { name: "MS Access Level II", price: 40 },
  { name: "MS Access Level I, II", price: 60 },
  { name: "Adobe Photoshop CC I", price: 35 },
  { name: "Adobe Photoshop Level II", price: 40 },
  { name: "Adobe Photoshop 1+2", price: 60 },
  { name: "CorelDRAW x22", price: 40 },
  { name: "Adobe Illustrator CC", price: 40 },
  { name: "Adobe Flash CC", price: 40 },
  { name: "Adobe InDesign CC", price: 40 },
  { name: "AutoCAD 2D", price: 50 },
  { name: "AutoCAD 2D for Mechanical", price: 70 },
  { name: "AutoCAD 2D for Construction & Architecture", price: 70 },
  { name: "AutoCAD 2D for Jewelry", price: 70 },
  { name: "AutoCAD 3D for Jewelry", price: 100 },
  { name: "AutoCAD 3D for Mechanical", price: 80 },
  { name: "SketchUp for Mechanical", price: 80 },
  { name: "SketchUp for Construction & Architecture", price: 80 },
  { name: "3D Render + Animation", price: 80 },
  { name: "3ds Max 2024", price: 70 },
  { name: "GIS Training", price: 60 },
  { name: "Microsoft Project", price: 70 },
  { name: "QuickBooks Premier", price: 45 },
  { name: "Peachtree Accounting", price: 60 },
  { name: "C Programming", price: 45 },
  { name: "C++ Programming", price: 45 },
  { name: "C# Programming", price: 70 },
  { name: "Python", price: 70 },
  { name: "Java Programming", price: 70 },
  { name: "Node.js", price: 70 },
  { name: "Laravel", price: 70 },
  { name: "HTML", price: 30 },
  { name: "CSS", price: 40 },
  { name: "PHP", price: 70 },
  { name: "jQuery or JavaScript", price: 50 },
  { name: "Bootstrap", price: 40 },
  { name: "SDL C + Advance GitHub", price: 30 },
  { name: "Spring Core + Spring Boot + PostgreSQL", price: 140 },
  { name: "SQL Server", price: 70 },
  { name: "MySQL", price: 40 },
  { name: "PostgreSQL", price: 30 },
  { name: "Tailwind CSS", price: 20 },
  { name: "ReactJS + TypeScript", price: 60 },
  { name: "NextJS + TypeScript", price: 60 },
  { name: "SST + S3", price: 30 },
  { name: "Git + GitHub", price: 20 },
  { name: "xpress + TypeScript + tsoa", price: 120 },
  { name: "AWS EC2 + Cognito", price: 35 },
  { name: "MongoDB", price: 50 },
  { name: "Docker", price: 30 },
  { name: "CI/CD", price: 15 },
  { name: "Adobe Flash", price: 40 },
  { name: "Sony Vegas", price: 40 },
  { name: "Cartoon Animation 2D", price: 99 },
  { name: "Adobe After Effects", price: 70 },
  { name: "Adobe Premiere", price: 70 },
  { name: "Particle Illusion", price: 20 },
  { name: "Cinema 4D", price: 70 },
  { name: "Daz3D Studio", price: 70 },
  { name: "FL Studio", price: 50 },
  { name: "Blender", price: 100 },
];

export function getCitoCoursePrice(courseName: string): number | undefined {
  const trimmed = courseName.trim();
  const row = CITO_COURSE_CATALOG.find((c) => c.name === trimmed);
  return row?.price;
}
